In [1]:
# Menghubungkan Colab dengan Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# Memanggil data set lewat gdrive
path = "/content/drive/MyDrive/Praktikum/praktikum04/Data/"

In [6]:
# Membaca file csv menggunakan pandas
import pandas as pd

df = pd.read_csv(path + 'day.csv')
df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600

In [24]:
# Membaca file csv menggunakan pandas
import pandas as pd

df = pd.read_csv(path + 'hour.csv')
df.head()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,0,1,1

In [11]:
import pandas as pd  # import sendiri supaya blok ini jalan sendiri
df_hour = pd.read_csv( path + 'hour.csv')

X = df_hour[['season','hum','windspeed']]
y = df_hour['temp']

X.head(), y.head()

(   season   hum  windspeed
 0       1  0.81        0.0
 1       1  0.80        0.0
 2       1  0.80        0.0
 3       1  0.75        0.0
 4       1  0.75        0.0,
 0    0.24
 1    0.22
 2    0.22
 3    0.24
 4    0.24
 Name: temp, dtype: float64)

In [12]:
import pandas as pd
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X_train.shape, X_test.shape

((13903, 3), (3476, 3))

In [13]:
import pandas as pd
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [14]:
import pandas as pd

y_pred = model.predict(X_test)
y_pred[:5]

array([0.57049436, 0.43831811, 0.57589914, 0.47823417, 0.41561611])

In [15]:
import pandas as pd
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.03224374142081836

In [17]:
import pandas as pd

df_day = pd.read_csv(path + 'day.csv')
df_day.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600

In [19]:
import pandas as pd

df_day = pd.read_csv(path + 'day.csv')

X = df_day[['season', 'hum', 'windspeed', 'casual', 'registered']]

y = df_day['temp']

X.head(), y.head()

(   season       hum  windspeed  casual  registered
 0       1  0.805833   0.160446     331         654
 1       1  0.696087   0.248539     131         670
 2       1  0.437273   0.248309     120        1229
 3       1  0.590435   0.160296     108        1454
 4       1  0.436957   0.186900      82        1518,
 0    0.344167
 1    0.363478
 2    0.196364
 3    0.200000
 4    0.226957
 Name: temp, dtype: float64)

In [20]:
import pandas as pd
from sklearn.model_selection import train_test_split

df_day = pd.read_csv(path + 'day.csv')
X = df_day[['season', 'hum', 'windspeed', 'casual', 'registered']]
y = df_day['temp']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X_train.shape, X_test.shape

((584, 5), (147, 5))

In [21]:
import pandas as pd
from sklearn.linear_model import LinearRegression

df_day = pd.read_csv(path + 'day.csv')
X = df_day[['season', 'hum', 'windspeed', 'casual', 'registered']]
y = df_day['temp']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [22]:
import pandas as pd

df_day = pd.read_csv(path + 'day.csv')
X = df_day[['season', 'hum', 'windspeed', 'casual', 'registered']]
y = df_day['temp']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_pred[:5]

array([0.61735545, 0.26266085, 0.45051657, 0.65087224, 0.64133824])

In [23]:
import pandas as pd
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

df_day = pd.read_csv(path + 'day.csv')
X = df_day[['season', 'hum', 'windspeed', 'casual', 'registered']]
y = df_day['temp']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.01771414338968397