In [3]:
# Menghubungkan Colab dengan Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [12]:
# Memanggil data set lewat gdrive
path = "/content/drive/MyDrive/Praktikum/praktikum03/Data/"

In [13]:
# Membaca file csv menggunakan pandas
import pandas as pd

df = pd.read_csv(path + 'socr.csv')
df.head()

   Index  Height(Inches)  Weight(Pounds)
0      1        65.78331        112.9925
1      2        71.51521        136.4873
2      3        69.39874        153.0269
3      4        68.21660        142.3354
4      5        67.78781        144.2971

In [14]:
# Membaca file csv menggunakan pandas
import pandas as pd

df = pd.read_csv(path + 'stunting_wasting_dataset.csv')
df.head()

,Jenis Kelamin,Umur (bulan),Tinggi Badan (cm),Berat Badan (kg),Stunting,Wasting
0,Laki-laki,19,91.6,13.3,Tall,Risk of Overweight
1,Laki-laki,20,77.7,8.5,Stunted,Underweight
2,Laki-laki,10,79.0,10.3,Normal,Risk of Overweight
3,Perempuan,2,50.3,8.3,Severely Stunted,Risk of Overweight
4,Perempuan,5,56.4,10.9,Severely Stunted,Risk of Overweight

In [15]:
df.describe()        # mean, std, min, quartiles, max
df.isnull().sum()    # cek missing values

Jenis Kelamin        0
Umur (bulan)         0
Tinggi Badan (cm)    0
Berat Badan (kg)     0
Stunting             0
Wasting              0
dtype: int64

In [17]:
print(df.columns)

Index(['Jenis Kelamin', 'Umur (bulan)', 'Tinggi Badan (cm)',
       'Berat Badan (kg)', 'Stunting', 'Wasting'],
      dtype='object')

In [18]:
df['tinggi_cm'] = df['Tinggi Badan (cm)']
df['berat_kg'] = df['Berat Badan (kg)']

df.head()

,Jenis Kelamin,Umur (bulan),Tinggi Badan (cm),Berat Badan (kg),Stunting,Wasting,tinggi_cm,berat_kg
0,Laki-laki,19,91.6,13.3,Tall,Risk of Overweight,91.6,13.3
1,Laki-laki,20,77.7,8.5,Stunted,Underweight,77.7,8.5
2,Laki-laki,10,79.0,10.3,Normal,Risk of Overweight,79.0,10.3
3,Perempuan,2,50.3,8.3,Severely Stunted,Risk of Overweight,50.3,8.3
4,Perempuan,5,56.4,10.9,Severely Stunted,Risk of Overweight,56.4,10.9